CXX = g++
CXXFLAGS = -O3 -std=c++11 -Wall -Wextra

decode_tag_binary: decode_tag_binary.cpp
	$(CXX) $(CXXFLAGS) -o decode_tag_binary decode_tag_binary.cpp

clean:
	rm -f decode_tag_binary

.PHONY: clean
