#!/bin/bash

# Create synthetic reads with realistic sequences
# Use some common sequences that are more likely to align

# Create R2 file (cDNA reads) 
cat > synthetic_R2.fastq << 'INNER_EOF'
@MUC20_test_read/2
ATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCG
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@DECR2_test_read/2
GCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGC
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
INNER_EOF

# Create R1 file (cell barcode + UMI) with valid format
cat > synthetic_R1.fastq << 'INNER_EOF'
@MUC20_test_read/1
AAACCCTTTGGGAAACCCCGGGGTTTAAAA
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@DECR2_test_read/1
AAACCCTTTGGGAAACCCCGGGGTTTAAAA
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIII
INNER_EOF

gzip -f synthetic_R1.fastq synthetic_R2.fastq
echo "Created synthetic files"
